# Generated by Django 5.0.4 on 2024-04-28 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisBibliografico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=255)),
                ('titulo', models.TextField()),
                ('resumen', models.TextField()),
                ('problema', models.TextField()),
                ('objetivos', models.TextField()),
                ('tipo_metodologia', models.CharField(max_length=100)),
                ('diseno_metodologia', models.CharField(max_length=100)),
                ('metodologia', models.TextField()),
                ('resultados', models.TextField()),
                ('conclusiones', models.TextField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='Introduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citacion', models.TextField()),
                ('titulo_articulo', models.CharField(max_length=255)),
                ('tema', models.TextField()),
                ('invest_problema', models.TextField()),
                ('invest_objetivo', models.TextField()),
                ('lenguaje_texto', models.CharField(max_length=10)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users')),
            ],
        ),
        migrations.DeleteModel(
            name='Introduction',
        ),
    ]
