# Generated by Django 5.0.4 on 2024-04-21 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation', models.TextField()),
                ('article_title', models.CharField(max_length=255)),
                ('topic', models.TextField()),
                ('reasearch_problem', models.TextField()),
                ('research_objetive', models.TextField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usuarios')),
            ],
        ),
    ]
