# Generated by Django 5.0.4 on 2024-04-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_analisisbibliografico_introduccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisisbibliografico',
            name='referentes_teoricos',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
