# Generated by Django 5.0.4 on 2024-04-21 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_usuarios_correo_introduction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Users',
        ),
    ]
