# Generated by Django 5.0.4 on 2024-04-29 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_analisisbibliografico_referentes_teoricos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analisisbibliografico',
            old_name='titulo',
            new_name='titulo_articulo',
        ),
        migrations.AddField(
            model_name='analisisbibliografico',
            name='citacion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analisisbibliografico',
            name='invest_objetivo',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analisisbibliografico',
            name='invest_problema',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analisisbibliografico',
            name='lenguaje_texto',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analisisbibliografico',
            name='tema',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Introduccion',
        ),
    ]
