# Generated by Django 5.0.4 on 2024-04-22 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_usuarios_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='introduction',
            old_name='reasearch_problem',
            new_name='research_problem',
        ),
    ]
