# Generated by Django 5.0.4 on 2024-04-29 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_titulo_analisisbibliografico_titulo_articulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analisisbibliografico',
            name='conclusiones',
        ),
        migrations.RemoveField(
            model_name='analisisbibliografico',
            name='diseno_metodologia',
        ),
        migrations.RemoveField(
            model_name='analisisbibliografico',
            name='invest_objetivo',
        ),
        migrations.RemoveField(
            model_name='analisisbibliografico',
            name='invest_problema',
        ),
        migrations.RemoveField(
            model_name='analisisbibliografico',
            name='lenguaje_texto',
        ),
        migrations.RemoveField(
            model_name='analisisbibliografico',
            name='metodologia',
        ),
        migrations.RemoveField(
            model_name='analisisbibliografico',
            name='objetivos',
        ),
        migrations.RemoveField(
            model_name='analisisbibliografico',
            name='problema',
        ),
        migrations.RemoveField(
            model_name='analisisbibliografico',
            name='referentes_teoricos',
        ),
        migrations.RemoveField(
            model_name='analisisbibliografico',
            name='resultados',
        ),
        migrations.RemoveField(
            model_name='analisisbibliografico',
            name='resumen',
        ),
        migrations.RemoveField(
            model_name='analisisbibliografico',
            name='tema',
        ),
        migrations.RemoveField(
            model_name='analisisbibliografico',
            name='tipo_metodologia',
        ),
        migrations.RemoveField(
            model_name='analisisbibliografico',
            name='titulo_articulo',
        ),
        migrations.RemoveField(
            model_name='analisisbibliografico',
            name='ubicacion',
        ),
        migrations.CreateModel(
            name='CargaAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citacion', models.TextField()),
                ('tema', models.TextField()),
                ('invest_problema', models.TextField()),
                ('invest_objetivo', models.TextField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('titulo_articulo', models.TextField()),
                ('resumen', models.TextField()),
                ('problema', models.TextField()),
                ('objetivos', models.TextField()),
                ('referentes_teoricos', models.TextField()),
                ('tipo_metodologia', models.CharField(max_length=100)),
                ('diseno_metodologia', models.CharField(max_length=100)),
                ('metodologia', models.TextField()),
                ('resultados', models.TextField()),
                ('conclusiones', models.TextField()),
                ('lenguaje_texto', models.CharField(max_length=10)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users')),
            ],
        ),
    ]
