# Generated by Django 5.0.4 on 2024-04-30 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_cargaanalisis_id_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajesSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_mensaje', models.CharField(max_length=255)),
                ('cuerpo_mensaje', models.TextField()),
                ('estado', models.CharField(max_length=100)),
                ('adjuntos', models.ImageField(upload_to='static/imagenes_soporte/')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario_origen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
