# Generated by Django 5.0.4 on 2024-05-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_mensajessoporte_adjuntos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargaanalisis',
            name='diseno_metodologia',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cargaanalisis',
            name='tipo_metodologia',
            field=models.TextField(),
        ),
    ]
