# Generated by Django 5.0.4 on 2024-05-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_cargaanalisis_diseno_metodologia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajessoporte',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default='2000-02-02 02:02:02.0'),
            preserve_default=False,
        ),
    ]
