# Generated by Django 5.0.4 on 2024-05-01 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_mensajessoporte_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajessoporte',
            name='fecha_creacion',
        ),
    ]
