# Generated by Django 5.0.4 on 2024-05-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_mensajessoporte_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajessoporte',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default='1900-02-02 20:20:20.0'),
            preserve_default=False,
        ),
    ]
