# Generated by Django 5.0.4 on 2024-05-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_mensajessoporte_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajessoporte',
            name='adjuntos',
            field=models.ImageField(blank=True, upload_to='myapp/static/imagenes_soporte/'),
        ),
    ]
