# Generated by Django 5.0.4 on 2024-05-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_mensajessoporte_adjuntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargaanalisis',
            name='ref_apa',
            field=models.TextField(default=''),
        ),
    ]
